ANDROID: sched: Provide prototype for the exported __balance_callbacks()
Commit 0fcb70851fbfe ("Makefile.extrawarn: turn on missing-prototypes
globally") enabled warnings for all missing prototypes which causes
errors due to the fact that we have -Werror enabled.

Provide missing prototype for the exported __balance_callbacks()
function in order to avoid the following build errors:

  kernel/sched/core.c:5172:6:
    error: no previous prototype for function '__balance_callbacks' [-Werror,-Wmissing-prototypes]

Fixes: 51ba045c81b3d ("ANDROID: GKI: vendor code needs __balance_callbacks access")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Id6c287d91e5ee95d6bf5ba0ab4af07a4025789d5