Revert "regulator: ab8500: Remove AB8505 USB regulator"
This reverts commit 5e210181f2e7989a5142ceba8c5363a757e4fa96,
which is commit 99c4f70df3a6446c56ca817c2d0f9c12d85d4e7c upstream.

Since this causes the following build error:

  arch/arm/mach-ux500/board-mop500-regulators.c:957:3:
    error: ‘AB8505_LDO_USB’ undeclared here (not in a function);
      did you mean ‘AB9540_LDO_USB’?
  arch/arm/mach-ux500/board-mop500-regulators.c:957:3:
    error: array index in initializer not of integer type

Change-Id: Iac8915a2b801102b13f4f815c3d0d4625e2312ee
Signed-off-by: Lee Jones <lee.jones@linaro.org>