Revert "Bluetooth: MGMT: Fix not checking if BT_HS is enabled"
This reverts commit af397d0efa00bc54c10aff845018794c461c6b8e.

Reverting due to build breakage.

 net/bluetooth/mgmt.c:1978:10: error: implicit declaration of function ‘mgmt_cmd_status’;
     did you mean ‘mgmt_status’? [-Werror=implicit-function-declaration]

Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: I3e6fe02f3cfb20e6be4106c433bc795fc8c595c8