ANDROID: sched: Provide prototype for exported set_next_entity()
Commit 0fcb70851fbfe ("Makefile.extrawarn: turn on missing-prototypes
globally") enabled warnings for all missing prototypes which causes
errors due to the fact that we have -Werror enabled.

Provide missing prototype for the exported set_next_entity() function in
order to avoid the following build errors:

  kernel/sched/fair.c:5442:6:
    error: no previous prototype for 'set_next_entity' [-Werror=missing-prototypes]

Fixes: f94f1b91143ed ("ANDROID: sched: Export set_next_entity")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I142030108aa94faa2029ab33e1d3b9c6fb8af581