Revert "of/unittest: Disable new dtc node_name_vs_property_name and interrupt_map warnings"
This reverts commit b68d0924ad8391d637f55bad0f987f8696a2d126 as it
breaks the build on clang-based systems with the errors:
	FATAL ERROR: Unrecognized check name "interrupt_map"
	FATAL ERROR: Unrecognized check name "node_name_vs_property_name"

Cc: Rob Herring <robh@kernel.org>
Fixes: b68d0924ad83 ("of/unittest: Disable new dtc node_name_vs_property_name and interrupt_map warnings")
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>
Change-Id: Ia90d9a1d73604f7f1cace2397fc97e3e35ce5b1c
Signed-off-by: Lee Jones <joneslee@google.com>