batman-adv: convert orig_node->vlan_list to hlist
[ Upstream commit d0fa4f3f5b0419a016ff27eea2fa615e4c0d1713 ]

Since the list's tail is never accessed using a double linked list head
wastes memory.

[Lee: Backported to Android-3.18 to fix the following build issue]

 In file included from ../include/linux/mutex.h:14,
                  from ../net/batman-adv/main.h:167,
                  from ../net/batman-adv/originator.c:18:
 ../net/batman-adv/originator.c: In function ‘batadv_orig_node_release’:
 ../include/linux/list.h:753:36: error: ‘struct list_head’ has no member named ‘first’
   for (pos = hlist_entry_safe((head)->first, typeof(*pos), member);\
                                    ^~

Signed-off-by: Marek Lindner <mareklindner@neomailbox.ch>
Signed-off-by: Antonio Quartulli <antonio@meshcoding.com>
Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: I2023de81078ff39cc887a7610a473754368397ee