clocksource/drivers/mxs_timer: Fix ‘clock_event_mode_label’ undeclared error
A recent back-ported commit removed '#if DEBUG'ery surrounding a piece
of code without removing the same from the declaration of a variable
used within.  This resulted in the following error which this patch
fixes:

  drivers/clocksource/mxs_timer.c:173:3: error: ‘clock_event_mode_label’ undeclared
  	(first use in this function); did you mean ‘clock_event_mode’?

Fixes: 88c0859600c2 ("clocksource/drivers/mxs_timer: Add missing semicolon when DEBUG is defined")
Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: I123624723c9262b2d784b42565c2354412e588c0